# Shell variables
# Generated by 'wal'
wallpaper='/home/municorn/.config/wpg/wallpapers/Road.jpg'

# Special
background='#10180a'
foreground='#f2fdff'
cursor='#f2fdff'

# Colors
color0='#10180a'
color1='#99AEC6'
color2='#8899AC'
color3='#979088'
color4='#748CA3'
color5='#93A5B9'
color6='#7698C4'
color7='#cad3de'
color8='#223415'
color9='#b0e0ff'
color10='#9cc5f3'
color11='#d6bc9e'
color12='#84b6e5'
color13='#a9d5ff'
color14='#85c2ff'
color15='#f2fdff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
