--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/municorn/.config/wpg/wallpapers/Road.jpg"

-- Special
background="#10180a"
foreground="#f2fdff"
cursor="#f2fdff"

-- Colors
color0="#10180a"
color1="#99AEC6"
color2="#8899AC"
color3="#979088"
color4="#748CA3"
color5="#93A5B9"
color6="#7698C4"
color7="#cad3de"
color8="#223415"
color9="#b0e0ff"
color10="#9cc5f3"
color11="#d6bc9e"
color12="#84b6e5"
color13="#a9d5ff"
color14="#85c2ff"
color15="#f2fdff"
