ln -s ./compton.conf ~/.config/compton.conf
ln -s ./dunst ~/.config/dunst
ln -s ./fish ~/.config/
ln -s ./gtk-3.0 ~/.config/
ln -s ./i3 ~/.config/
ln -s ./kitty ~/.config
ln -s ./mimeapps.list ~/.config/
ln -s ./mopidy ~/.config/
ln -s ./nvim ~/.config/
ln -s ./ranger ~/.config/
ln -s ./redshift ~/.config/
ln -s ./rofi ~/.config/
ln -s ./termite ~/.config/
ln -s ./wpg ~/.config/
