# TO GENERATE, RUN npm run build -- contents::iosevka-muse

[buildPlans.iosevka-muse] # <iosevka-muse> is your plan name
family = "Iosevka Muse"   # Font menu family name
design = ["sp-fixed", "VXBS", "VXBQ", "cv98", "cv27", "VXBA", "cv72", "cv78", "cv92", "cv83", "VXAB", "VXAE", "cv96", "cv95", "cv19", "cv38", "cv36", "cv81", "cv74", "cv49", "cv76", "VXBT", "cv85", "cv69", "cv88"] # Custom styles

 [buildPlans.iosevka-muse.weights.regular]
 shape = 400  # Weight for glyph shapes.
 menu  = 400  # Weight for the font's names.
 css   = 400  # Weight for webfont CSS.
 
 [buildPlans.iosevka-muse.weights.bold]
 shape = 700
 menu  = 700
 css   = 700
