#!/bin/bash

$HOME/.config/bspwm/autoworkspaces.sh &

$HOME/.config/bspwm/wallpaper.sh &
$HOME/.config/wpg/wp_init.sh &

xsetroot -cursor_name left_ptr &

killall muse-status
killall lemonbar
$HOME/.config/bspwm/panel.sh &

bspc config border_width         4
bspc config normal_border_color  "#10180a"
bspc config active_border_color  "#496a8c"
bspc config focused_border_color "#6a9bcb"

bspc config window_gap           8

bspc config split_ratio                 0.5
bspc config click_to_focus              button1
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config pointer_follows_monitor     true
bspc config single_monocle              false

bspc rule -a spotify desktop='9' follow=on
bspc rule -a Onboard state=floating
# bspc rule -a Gimp state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

xinput map-to-output 11 eDP &
xinput map-to-output 12 eDP &
xinput map-to-output 17 eDP &
