["/home/municorn/Pictures/Wallpapers/Photos/Tower.jpg"]
maroon = "#797967"
olive = "#7d827b"
green = "#8c939a"
teal = "#8e969e"
navy = "#8a929b"
purple = "#737986"
red = "#c6c6a8"
yellow = "#c6cfc4"
lime = "#d1dce6"
aqua = "#d2dfea"
blue = "#ced8e8"
magenta = "#b5bed2"
black = "#07090c"
silver = "#a0a9b2"
gray = "#1a2026"
white = "#e5f2ff"
dark_accent = "#7947b2"
accent = "#9b3bff"

["/home/municorn/Pictures/Wallpapers/Photos/Bells.JPG"]
maroon = "#876476"
olive = "#67715a"
green = "#4c7140"
teal = "#417141"
navy = "#677e7c"
purple = "#897098"
red = "#d49db9"
yellow = "#afbe97"
lime = "#8abd81"
aqua = "#83be83"
blue = "#a7cac7"
magenta = "#cea9e4"
black = "#070c07"
silver = "#a2b2a0"
gray = "#1b261a"
white = "#e7ffe5"
dark_accent = "#47b2a8"
accent = "#3fffe9"

["/home/municorn/Pictures/Wallpapers/Photos/Branch.jpg"]
maroon = "#7e6572"
olive = "#8b5951"
green = "#9c5a42"
teal = "#a55e33"
navy = "#b07738"
purple = "#735b3f"
red = "#cba3b7"
yellow = "#d88a7e"
lime = "#e98459"
aqua = "#f18140"
blue = "#fca647"
magenta = "#c0a379"
black = "#0c0907"
silver = "#b2a6a0"
gray = "#261e1a"
white = "#ffede5"
dark_accent = "#91b247"
accent = "#c3ff42"

["/home/municorn/Pictures/Wallpapers/Photos/Balcony.jpg"]
maroon = "#867776"
olive = "#8c6449"
green = "#8b6548"
teal = "#987f61"
navy = "#877f62"
purple = "#757782"
red = "#d3bbba"
yellow = "#d89b72"
lime = "#d89e70"
aqua = "#e4bf91"
blue = "#d3c89a"
magenta = "#babdce"
black = "#0c0907"
silver = "#b2a8a0"
gray = "#26201a"
white = "#fff1e5"
dark_accent = "#7fb247"
accent = "#a7ff3e"

["/home/municorn/Pictures/Wallpapers/Photos/Trees.jpg"]
maroon = "#69824c"
olive = "#4c783f"
green = "#407540"
teal = "#407458"
navy = "#447669"
purple = "#617681"
red = "#aacf78"
yellow = "#85c56c"
lime = "#83c183"
aqua = "#84c09c"
blue = "#8bc3b5"
magenta = "#9abcce"
black = "#070c08"
silver = "#a0b2a4"
gray = "#1a261d"
white = "#e5ffea"
dark_accent = "#479db2"
accent = "#3cd4ff"

["/home/municorn/Pictures/Wallpapers/Photos/Palm.jpg"]
maroon = "#7996a2"
olive = "#6082b2"
green = "#577ab2"
teal = "#5375b2"
navy = "#5173b2"
purple = "#506fb1"
red = "#b3dcee"
yellow = "#89bafe"
lime = "#7daffe"
aqua = "#77a8fe"
blue = "#74a4fe"
magenta = "#73a0fd"
black = "#0a0b0c"
silver = "#a0a7b2"
gray = "#1e2126"
white = "#e5efff"
dark_accent = "#8747b2"
accent = "#b74cff"

["/home/municorn/Pictures/Wallpapers/Photos/Coaster.jpg"]
maroon = "#867264"
olive = "#846e48"
green = "#7e723f"
teal = "#6a733f"
navy = "#71828e"
purple = "#858799"
red = "#d2b39e"
yellow = "#d1ae72"
lime = "#cbba70"
aqua = "#b2c06e"
blue = "#aec9da"
magenta = "#c7cbe5"
black = "#0c0c07"
silver = "#b2b1a0"
gray = "#26251a"
white = "#fffde5"
dark_accent = "#4cb247"
accent = "#4bff3d"

["/home/municorn/Pictures/Wallpapers/Photos/Blossom.jpg"]
maroon = "#a6929c"
olive = "#a48d90"
green = "#a4908b"
teal = "#a3a197"
navy = "#9aa198"
purple = "#9aa0a5"
red = "#f2d6e3"
yellow = "#f0cfd3"
lime = "#f0d3cb"
aqua = "#efeddf"
blue = "#e3ede0"
magenta = "#e2eaf2"
black = "#090c07"
silver = "#7eb26d"
gray = "#182617"
white = "#b5ff9b"
dark_accent = "#47b293"
accent = "#49ffcc"

["/home/municorn/Drive/Documents/Wallpapers/Scenes/Mists.jpg"]
maroon = "#968774"
olive = "#757c40"
green = "#768380"
teal = "#7e8890"
navy = "#7c8791"
purple = "#828a94"
red = "#e2ccb0"
yellow = "#c4c883"
lime = "#bccfcb"
aqua = "#c1d0dd"
blue = "#becfde"
magenta = "#c6d2e0"
black = "#070b0c"
silver = "#a0abb2"
gray = "#1a2026"
white = "#e5f4ff"
dark_accent = "#7047b2"
accent = "#8e3aff"

["/home/municorn/Pictures/Wallpapers/Photos/Sunset.jpg"]
maroon = "#9e6958"
olive = "#ad8651"
green = "#a9a17f"
teal = "#87949a"
navy = "#71899f"
purple = "#66748a"
red = "#ea9b83"
yellow = "#fabe6b"
lime = "#f5eab9"
aqua = "#cadee7"
blue = "#a7caec"
magenta = "#9fb4d6"
black = "#090c07"
silver = "#a6b2a0"
gray = "#1e261a"
white = "#eeffe5"
dark_accent = "#47b28d"
accent = "#41ffc0"
