["/home/municorn/Drive/Documents/Wallpapers/Scenes/Mists.jpg"]
maroon = "#968774"
olive = "#7a7c52"
green = "#768380"
teal = "#7e8890"
navy = "#7c8791"
purple = "#828a94"
red = "#e2ccb0"
yellow = "#c5c884"
lime = "#bccfcb"
aqua = "#c1d0dd"
blue = "#becfde"
magenta = "#c6d2e0"
black = "#080b0c"
silver = "#a0abb2"
gray = "#1a2126"
white = "#e5f4ff"
dark_accent = "#7347b2"
accent = "#954cff"
