["/home/municorn/Pictures/Wallpapers/Photos/Trees.jpg"]
maroon = "#69824c"
olive = "#4f7840"
green = "#4e754e"
teal = "#4e745d"
navy = "#52766e"
purple = "#617681"
red = "#aacf78"
yellow = "#85c56c"
lime = "#83c183"
aqua = "#84c09c"
blue = "#8bc3b5"
magenta = "#9abcce"
black = "#070c08"
silver = "#a0b2a4"
gray = "#1a261d"
white = "#e5ffea"
dark_accent = "#479db2"
accent = "#4adaff"

["/home/municorn/Drive/Documents/Wallpapers/Scenes/Mists.jpg"]
maroon = "#968774"
olive = "#797c4e"
green = "#768380"
teal = "#7e8890"
navy = "#7c8791"
purple = "#828a94"
red = "#e2ccb0"
yellow = "#c4c883"
lime = "#bccfcb"
aqua = "#c1d0dd"
blue = "#becfde"
magenta = "#c6d2e0"
black = "#070b0c"
silver = "#a0abb2"
gray = "#1a2026"
white = "#e5f4ff"
dark_accent = "#7047b2"
accent = "#9448ff"

["/home/municorn/Pictures/Wallpapers/Photos/Balcony.jpg"]
maroon = "#867776"
olive = "#8c6449"
green = "#8b6648"
teal = "#987f61"
navy = "#877f62"
purple = "#757782"
red = "#d3bbba"
yellow = "#d89b72"
lime = "#d89e70"
aqua = "#e4bf92"
blue = "#d3c89a"
magenta = "#babdce"
black = "#0c0a08"
silver = "#b2a8a0"
gray = "#26201a"
white = "#fff1e5"
dark_accent = "#80b247"
accent = "#abff4c"

["/home/municorn/Pictures/Wallpapers/Photos/Coaster.jpg"]
maroon = "#867264"
olive = "#846e48"
green = "#7e7445"
teal = "#6b7341"
navy = "#71828e"
purple = "#858799"
red = "#d2b39e"
yellow = "#d1ae72"
lime = "#cbba70"
aqua = "#b2c06e"
blue = "#aec9da"
magenta = "#c7cbe5"
black = "#0c0c07"
silver = "#b2b1a0"
gray = "#26251a"
white = "#fffde5"
dark_accent = "#4cb247"
accent = "#55ff4b"

["/home/municorn/Pictures/Wallpapers/Photos/Tower.jpg"]
maroon = "#797967"
olive = "#7d827b"
green = "#8c939a"
teal = "#8e969e"
navy = "#8a929b"
purple = "#737986"
red = "#c6c6a8"
yellow = "#c6cfc4"
lime = "#d1dce6"
aqua = "#d2dfea"
blue = "#ced8e8"
magenta = "#b5bed2"
black = "#07090c"
silver = "#a0a9b2"
gray = "#1a2026"
white = "#e5f2ff"
dark_accent = "#7947b2"
accent = "#a449ff"
