["/home/municorn/Pictures/Wallpapers/Photos/Trees.jpg"]
maroon = "#6a824c"
olive = "#507841"
green = "#4f754f"
teal = "#4f745d"
navy = "#53766e"
purple = "#617681"
red = "#aacf78"
yellow = "#85c56c"
lime = "#83c183"
aqua = "#84c09c"
blue = "#8bc3b5"
magenta = "#9abcce"
black = "#070c08"
silver = "#a0b2a4"
gray = "#1a261d"
white = "#e5ffea"
dark_accent = "#479db2"
accent = "#4bdaff"

["/home/municorn/Drive/Documents/Wallpapers/Scenes/Mists.jpg"]
maroon = "#968774"
olive = "#7a7c4f"
green = "#768380"
teal = "#7e8890"
navy = "#7c8791"
purple = "#828a94"
red = "#e2ccb0"
yellow = "#c4c883"
lime = "#bccfcb"
aqua = "#c1d0dd"
blue = "#becfde"
magenta = "#c6d2e0"
black = "#070b0c"
silver = "#a0abb2"
gray = "#1a2026"
white = "#e5f4ff"
dark_accent = "#7047b2"
accent = "#9449ff"

["/home/municorn/Pictures/Wallpapers/Photos/Tower.jpg"]
maroon = "#797967"
olive = "#7d827b"
green = "#8c939a"
teal = "#8e969e"
navy = "#8a929b"
purple = "#737986"
red = "#c6c6a8"
yellow = "#c6cfc4"
lime = "#d1dce6"
aqua = "#d2dfea"
blue = "#ced8e8"
magenta = "#b5bed2"
black = "#07090c"
silver = "#a0a9b2"
gray = "#1a2026"
white = "#e5f2ff"
dark_accent = "#7a47b2"
accent = "#a54aff"

["/home/municorn/Pictures/Wallpapers/Photos/Coaster.jpg"]
maroon = "#867264"
olive = "#846e48"
green = "#7e7446"
teal = "#6b7342"
navy = "#71838e"
purple = "#858799"
red = "#d2b39e"
yellow = "#d1ae72"
lime = "#cbba70"
aqua = "#b3c06e"
blue = "#aecada"
magenta = "#c7cbe5"
black = "#0c0c08"
silver = "#b2b1a0"
gray = "#26251a"
white = "#fffde5"
dark_accent = "#4db247"
accent = "#56ff4c"
